sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx1e3242955e318e24
    secret: 0db1801c9c6d1c0e0b225961086b0ebb

  alioss:
    #    oss-cn-hangzhou.aliyuncs.com
    endpoint: oss-cn-beijing.aliyuncs.com
    #     LTAI5tPeFLzsPPT8gG3LPW64
    accessKeyId: LTAI5tSZJag9omH1HmpGEXqE
    #    U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    accessKeySecret: Vqnqx3hJpVZ2hzeCiPMdLv31SP3A9l
    bucketName: sky-take-out-char