sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx1e3242955e318e24
    secret: 0db1801c9c6d1c0e0b225961086b0ebb
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://5479f53d.r6.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
  alioss:
    #    oss-cn-hangzhou.aliyuncs.com
    endpoint: oss-cn-beijing.aliyuncs.com
    #     LTAI5tPeFLzsPPT8gG3LPW64
    accessKeyId: LTAI5tSZJag9omH1HmpGEXqE
    #    U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    accessKeySecret: Vqnqx3hJpVZ2hzeCiPMdLv31SP3A9l
    bucketName: sky-take-out-char